name: Build and Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install cibuildwheel under 3
        run: python -m pip install 'cibuildwheel<3'

      - name: Build wheels with cibuildwheel with cp37
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp37-*"
          CIBW_ARCHS_MACOS: universal2

      - name: Install cibuildwheel
        run: python -m pip install -U 'cibuildwheel==3.2.0'

      - name: Build wheels with cibuildwheel
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-* cp314-*"
          CIBW_ARCHS_MACOS: universal2

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-wheels-${{ matrix.os }}-${{ github.run_id }}
          path: dist

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/python-neo-lzf

    steps:
      - name: Download Ubuntu wheels
        uses: actions/download-artifact@v4
        with:
          name: built-wheels-ubuntu-latest-${{ github.run_id }}
          path: dist

      - name: Download Windows wheels
        uses: actions/download-artifact@v4
        with:
          name: built-wheels-windows-latest-${{ github.run_id }}
          path: dist

      - name: Download macOS wheels
        uses: actions/download-artifact@v4
        with:
          name: built-wheels-macos-latest-${{ github.run_id }}
          path: dist

      - name: Publish to PyPI via Trusted Publisher
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: dist

